name: 'publish'

on:
  push:
    branches:
      - release
jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - name: run eslint check
        run: yarn lint-check
